const M = (question, options, answer, solution, mistake) => ({ question, options, correct: [answer], solution, mistake });
const S = (question, options, answers, solution, mistake) => ({ question, options, correct: answers, solution, mistake, type: 'MSQ' });
const N = (question, value, solution, mistake, tolerance = 0.01) => ({ question, value, solution, mistake, tolerance });

export const questionSeeds = {
  'probability-statistics:1': [
    M('How many three-letter strings with distinct letters can be formed from five distinct letters?', ['10', '20', '60', '125'], 'C', 'Order matters and repetition is forbidden, so ${}^5P_3=5\\cdot4\\cdot3=60$.', 'Using ${5\\choose3}$ ignores the order of the letters.'),
    M('Two fair dice are rolled. What is $P(\\text{sum}=7)$?', ['$1/12$', '$1/6$', '$5/36$', '$7/36$'], 'B', 'The six ordered pairs $(1,6),\\ldots,(6,1)$ work out of 36 equally likely pairs, giving $6/36=1/6$.', 'Treating unordered pairs as equally likely changes the sample space.'),
    M('If $A$ and $B$ are mutually exclusive with $P(A)=0.3$ and $P(B)=0.4$, then $P(A\\cup B)$ is', ['$0.12$', '$0.58$', '$0.7$', '$1$'], 'C', 'Mutual exclusivity gives $P(A\\cap B)=0$, so $P(A\\cup B)=0.3+0.4=0.7$.', 'Multiplying applies to independent intersections, not disjoint unions.'),
    M('Which set must be an event in every probability model?', ['Only the sample space', 'Only the empty set', 'Both the empty set and sample space', 'Every subset, even for an arbitrary sigma-algebra'], 'C', 'Every sigma-algebra contains $\\varnothing$ and $\\Omega$. It need not contain every subset when $\\Omega$ is uncountable.', 'A sample space does not force the power set to be the event collection.'),
    M('For any event $A$ with $P(A)=0.27$, $P(A^c)$ equals', ['$0.27$', '$0.63$', '$0.73$', '$1.27$'], 'C', '$P(A^c)=1-P(A)=0.73$.', 'The complement is subtracted from one, not from the sample size.'),
    M('Ten people form a committee of three. How many committees are possible?', ['30', '120', '720', '1000'], 'B', 'Membership has no roles, so use ${10\\choose3}=120$.', 'A committee is unordered; permutations overcount each committee by $3!$.'),
    S('Which statements are always true for events $A,B$?', ['$P(A\\cap B)\\le P(A)$', '$P(A\\cup B)\\ge P(A)$', '$P(A\\cup B)=P(A)+P(B)$', '$P(A^c)=1-P(A)$'], ['A', 'B', 'D'], 'Intersection is contained in $A$, union contains $A$, and complementation gives the last identity. Additivity without subtraction requires disjointness.', 'Do not use the disjoint-union formula without the disjointness condition.'),
    M('If independent events $A,B$ satisfy $P(A)=1/2$ and $P(A\\cup B)=3/4$, then $P(B)$ is', ['$1/4$', '$1/3$', '$1/2$', '$3/4$'], 'C', '$3/4=1/2+p-(1/2)p=1/2+p/2$, so $p=1/2$.', 'Independence determines the intersection, not the union directly.'),
    M('Which pair of events from one fair die roll is independent?', ['$A=\\{1\\},B=\\{2\\}$', '$A=\\{1,2,3\\},B=\\{1,4\\}$', '$A=\\{1,2\\},B=\\{1,2,3\\}$', '$A=\\{1,2,3\\},B=A^c$'], 'B', '$P(A)=1/2$, $P(B)=1/3$, and $P(A\\cap B)=P(\\{1\\})=1/6=P(A)P(B)$, so the second pair is independent.', 'Always verify the product rule exactly.'),
    M('A password has two distinct letters followed by two distinct digits. Reuse is forbidden within each group. The count is', ['$26^2\\cdot10^2$', '$26\\cdot25\\cdot10\\cdot9$', '${26\\choose2}{10\\choose2}$', '$36\\cdot35\\cdot34\\cdot33$'], 'B', 'Positions are ordered: $26P2\\times10P2=26\\cdot25\\cdot10\\cdot9$.', 'Choosing unordered letter/digit sets loses positional order.'),
    N('How many binary strings of length 8 contain exactly three ones?', 56, '${8\\choose3}=56$: choose the three positions occupied by ones.', 'Do not arrange the chosen ones again; they are identical.', 0),
    N('How many nonnegative integer solutions satisfy $x+y+z=10$?', 66, 'Stars and bars gives ${12\\choose2}=66$.', 'Nonnegative solutions use $n+k-1$ positions; positive solutions use a shifted total.', 0),
    N('How many positive integer solutions satisfy $x_1+x_2+x_3+x_4=10$?', 84, 'Set $y_i=x_i-1\\ge0$. Then $\\sum y_i=6$, giving ${9\\choose3}=84$.', 'Account for the mandatory one in every variable before applying stars and bars.', 0),
    N('From 7 men and 5 women, how many 4-person committees contain exactly 2 women?', 210, 'Choose independently: ${5\\choose2}{7\\choose2}=10\\cdot21=210$.', 'The order of committee members is irrelevant.', 0),
    N('A fair coin is tossed 5 times. Enter $32P(\\text{at least one head})$.', 31, '$P(\\text{no heads})=1/32$, so the requested scaled probability is $32(31/32)=31$.', '“At least one” is fastest through its complement.', 0),
    N('Events $A,B$ have $P(A)=0.6$, $P(B)=0.5$, and $P(A\\cup B)=0.8$. Enter $10P(A\\cap B)$.', 3, 'Inclusion–exclusion gives $P(A\\cap B)=0.6+0.5-0.8=0.3$; scaling gives 3.', 'Subtract the union; do not assume independence.', 0),
    N('A box contains 4 red, 3 blue, and 2 green balls. Two are drawn without replacement. How many unordered pairs have different colors?', 26, 'Count cross-color pairs: $4\\cdot3+4\\cdot2+3\\cdot2=12+8+6=26$.', 'Within a cross-color pair there is no extra factor of two.', 0),
    N('How many onto functions exist from a 3-element set to a 2-element set?', 6, 'There are $2^3=8$ functions; exclude the two constant functions, leaving 6.', 'Onto excludes functions that miss either codomain element.', 0),
    N('A fair die is rolled twice. Enter $36P(\\text{the second result exceeds the first})$.', 15, 'There are ${6\\choose2}=15$ ordered increasing pairs among 36 outcomes.', 'The six ties prevent a simple one-half of all 36 outcomes.', 0),
    N('In a class of 30, 18 know Python, 14 know SQL, and 5 know neither. How many know both?', 7, '$|P\\cup S|=25$, so $|P\\cap S|=18+14-25=7$.', 'Convert “neither” into the union size first.', 0)
  ],

  'probability-statistics:2': [
    M('If $P(A\\cap B)=0.18$ and $P(B)=0.30$, then $P(A\\mid B)$ is', ['$0.12$', '$0.48$', '$0.60$', '$1.67$'], 'C', '$P(A\\mid B)=0.18/0.30=0.60$.', 'Conditional probability divides by the probability of the condition.'),
    M('A test has sensitivity 0.9. This means', ['$P(D\\mid +)=0.9$', '$P(+\\mid D)=0.9$', '$P(-\\mid D^c)=0.9$', '$P(D^c\\mid -)=0.9$'], 'B', 'Sensitivity is the true-positive rate $P(+\\mid D)$.', 'Sensitivity is not the posterior probability of disease.'),
    M('For a joint PMF $p(x,y)$, the marginal $p_X(x)$ is obtained by', ['maximizing over $y$', 'summing over $y$', 'dividing by $p_Y(y)$', 'summing over $x$'], 'B', 'Marginalization removes $Y$: $p_X(x)=\\sum_y p(x,y)$.', 'Divide by a marginal only when forming a conditional distribution.'),
    M('If $A$ and $B$ are independent and $P(B)>0$, then $P(A\\mid B)$ equals', ['$0$', '$P(B)$', '$P(A)$', '$P(A\\cap B)$'], 'C', 'Independence says conditioning on $B$ does not change $A$: $P(A\\mid B)=P(A)$.', 'This requires the conditioning event to have positive probability.'),
    M('Which denominator appears in Bayes’ theorem for causes $C_i$ partitioning the sample space?', ['$P(C_i)$', '$P(E\\mid C_i)$', '$\\sum_jP(E\\mid C_j)P(C_j)$', '$\\sum_jP(C_j\\mid E)$'], 'C', 'The denominator is $P(E)$ expanded by total probability across the cause partition.', 'The denominator must normalize across every possible cause.'),
    M('If $p_{X,Y}(x,y)=p_X(x)p_Y(y)$ for every support point, then $X,Y$ are', ['mutually exclusive', 'independent', 'identically distributed', 'uncorrelated only'], 'B', 'Factorization of the full joint distribution is the definition of independence.', 'Checking only equality of marginals does not establish independence.'),
    S('A partition $C_1,\\ldots,C_k$ satisfies which properties?', ['The events are pairwise disjoint', 'Their union is the sample space', 'Every $P(C_i)$ is equal', 'Each outcome lies in exactly one part'], ['A', 'B', 'D'], 'A partition is exhaustive and pairwise disjoint, so every outcome belongs to exactly one part. Equal probabilities are unnecessary.', 'Partition refers to set structure, not equal likelihood.'),
    M('Suppose $P(A)=.4$, $P(B)=.5$, $P(A\\mid B)=.4$. Then $A$ and $B$ are', ['independent', 'mutually exclusive', 'complements', 'impossible to classify'], 'A', '$P(A\\mid B)=P(A)$ with $P(B)>0$, hence independence.', 'Equal conditional and marginal probability is a valid independence test.'),
    M('A fair coin is tossed twice. Given at least one head, the probability of two heads is', ['$1/4$', '$1/3$', '$1/2$', '$2/3$'], 'B', 'The reduced equally likely sample space is $\\{HH,HT,TH\\}$; one of three has two heads.', 'After conditioning, $TT$ is no longer in the sample space.'),
    M('For continuous variables, $f_{X\\mid Y}(x\\mid y)$ equals', ['$f_{X,Y}(x,y)/f_X(x)$', '$f_{X,Y}(x,y)/f_Y(y)$', '$f_X(x)f_Y(y)$', '$f_Y(y)/f_{X,Y}(x,y)$'], 'B', 'Normalize the joint slice at $Y=y$ by its marginal density $f_Y(y)$.', 'The denominator corresponds to the variable after the conditioning bar.'),
    N('A factory has machines A and B producing 60% and 40% of items, with defect rates 2% and 5%. Enter $1000P(A\\mid\\text{defect})$.', 375, '$P(D)=.6(.02)+.4(.05)=.032$. Thus $P(A\\mid D)=.012/.032=.375$ and the scaled result is 375.', 'Weight defect rates by production shares in the denominator.', 0),
    N('Given $P(A)=0.5$, $P(B\\mid A)=0.8$, and $P(B\\mid A^c)=0.2$, enter $10P(B)$.', 5, 'Total probability gives $P(B)=.8(.5)+.2(.5)=.5$; scaling gives 5.', 'Include both the $A$ and $A^c$ routes.'),
    N('A joint PMF is $p(x,y)=c(x+y)$ for $x,y\\in\\{1,2\\}$. Enter $10c$.', 0.833333333, 'The four weights are 2,3,3,4 and sum to 12, so $c=1/12$. The requested value is $10/12=5/6$.', 'Normalize over every ordered support pair.', 0.001),
    N('For the joint masses $p(0,0)=.1,p(0,1)=.2,p(1,0)=.3,p(1,1)=.4$, enter $10P(Y=1\\mid X=1)$.', 5.714285714, '$P(Y=1\\mid X=1)=.4/(.3+.4)=4/7$, so multiplying by 10 gives $40/7\\approx5.714$.', 'Normalize within the row $X=1$, not by the overall total.'),
    N('Two cards are drawn without replacement from a standard deck. Enter $1000P(\\text{second is ace}\\mid\\text{first is ace})$.', 58.823529, 'After an ace is drawn, 3 aces remain among 51 cards: $3/51=1/17$. Scaling gives $1000/17\\approx58.824$.', 'Without replacement changes both numerator and denominator.'),
    N('Box 1 is selected with probability .3 and has 2 red of 5 balls. Box 2 is selected otherwise and has 6 red of 10. Enter $100P(\\text{Box 1}\\mid\\text{red})$.', 22.222222, '$P(R)=.3(.4)+.7(.6)=.54$. Bayes gives $.12/.54=2/9$, so the scaled value is $22.222\\ldots$.', 'Use the selection probabilities as priors.'),
    N('If $P(A\\mid B)=.7$, $P(B)=.4$, and $P(A)=.5$, enter $100P(B\\mid A)$.', 56, '$P(A\\cap B)=.7(.4)=.28$, so $P(B\\mid A)=.28/.5=.56$ and the result is 56.', 'Reverse conditioning through the joint probability.'),
    N('A family has two children with independent, equally likely sexes. Given at least one is a girl, enter $3P(\\text{both girls})$.', 1, 'The conditional space is $\\{GG,GB,BG\\}$; probability is $1/3$, and scaling by 3 gives 1.', 'Birth order makes $GB$ and $BG$ distinct outcomes.'),
    N('The density $f(x,y)=c$ on $0<y<x<1$. Enter $10c$.', 20, 'The triangular support has area $1/2$. Normalization gives $c(1/2)=1$, so $c=2$ and $10c=20$.', 'Integrate over the triangular support, not the full unit square.', 0),
    N('If $X,Y$ are independent, $P(X\\le2)=.4$ and $P(Y>3)=.25$, enter $100P(X\\le2,Y>3)$.', 10, 'Independence gives $.4(.25)=.10$, so the scaled result is 10.', 'The multiplication is justified here by independence.', 0)
  ],

  'probability-statistics:3': [
    M('A Bernoulli random variable can take values', ['$0$ only', '$1$ only', '$0$ and $1$', 'every nonnegative integer'], 'C', 'Bernoulli records one binary outcome, conventionally 0 or 1.', 'Binomial, not Bernoulli, counts multiple successes.'),
    M('If $X\\sim Bin(n,p)$, then $E[X]$ is', ['$p$', '$np$', '$n(1-p)$', '$np(1-p)$'], 'B', 'A binomial is a sum of $n$ Bernoulli variables, so its mean is $np$.', '$np(1-p)$ is the variance.'),
    M('If $X\\sim Pois(\\lambda)$, which equality holds?', ['$E[X]=\\lambda,Var(X)=\\lambda$', '$E[X]=0,Var(X)=\\lambda$', '$E[X]=\\lambda,Var(X)=\\lambda^2$', '$E[X]=1/\\lambda$'], 'A', 'For a Poisson variable both mean and variance equal the rate $\\lambda$.', 'The exponential mean $1/\\lambda$ belongs to a different distribution.'),
    M('Which is a valid PMF property?', ['$p(x)<0$ is allowed if totals cancel', '$\\sum_xp(x)=1$', '$p(x)$ must be increasing', '$p(x)\\le1/n$ on $n$ points'], 'B', 'Masses are nonnegative and sum to one. No monotonicity is required.', 'Individual masses need not be equal.'),
    M('For discrete uniform $X$ on $\\{1,2,3,4,5\\}$, $E[X]$ is', ['$2$', '$2.5$', '$3$', '$3.5$'], 'C', 'The mean of consecutive endpoints is $(1+5)/2=3$.', 'Include both endpoints in the support.'),
    M('The sum of independent $Pois(2)$ and $Pois(5)$ variables follows', ['$Pois(3)$', '$Pois(7)$', '$Bin(7,1/2)$', '$N(7,7)$ exactly'], 'B', 'Independent Poisson variables add their rates, giving $Pois(7)$.', 'Normality is only an approximation at large rates.'),
    S('For any integrable discrete random variables $X,Y$, which are true?', ['$E[X+Y]=E[X]+E[Y]$', '$E[3X]=3E[X]$', '$E[XY]=E[X]E[Y]$ always', '$E[c]=c$'], ['A', 'B', 'D'], 'Expectation is linear and constants remain constants. Products factor only under suitable independence.', 'Linearity does not require independence; product factorization does.'),
    M('A count of successes in 12 independent trials with success probability .3 is modeled by', ['$Bernoulli(.3)$', '$Bin(12,.3)$', '$Pois(.3)$', '$Uniform\\{0,\\ldots,12\\}$'], 'B', 'Fixed trial count, identical probability, independence, and success count are the binomial setup.', 'Bernoulli models only one trial.'),
    M('For $X\\sim Bin(n,p)$, $P(X=0)$ equals', ['$p^n$', '$(1-p)^n$', '$1-p^n$', '$e^{-np}$ exactly'], 'B', 'Zero successes means all $n$ trials fail: $(1-p)^n$.', '$e^{-np}$ is a possible approximation, not the exact binomial value.'),
    M('If $Y=2X+3$, then $Var(Y)$ is', ['$2Var(X)+3$', '$4Var(X)$', '$4Var(X)+3$', '$Var(X)+3$'], 'B', 'Variance scales by the square: $Var(2X+3)=4Var(X)$.', 'The additive constant does not affect spread.'),
    N('For $X\\sim Bin(10,0.2)$, enter $E[X]$.', 2, '$E[X]=np=10(.2)=2$.', 'Do not use the variance formula.', 0),
    N('For $X\\sim Bin(10,0.2)$, enter $Var(X)$.', 1.6, '$Var(X)=np(1-p)=10(.2)(.8)=1.6$.', 'Include the failure probability factor.', 0.001),
    N('A PMF is $p(k)=ck$ for $k=1,2,3,4$. Enter $10c$.', 1, '$c(1+2+3+4)=10c=1$, so the requested value is 1.', 'Normalization uses the sum of all masses.', 0),
    N('For that PMF $p(k)=k/10$, enter $10E[X]$.', 30, '$E[X]=\\sum k(k/10)=(1+4+9+16)/10=3$, so $10E[X]=30$.', 'Expectation multiplies each value by its probability.', 0),
    N('If $X\\sim Pois(3)$, enter $1000P(X=0)$ rounded to two decimals.', 49.787068, '$P(X=0)=e^{-3}$, so $1000e^{-3}\\approx49.787$.', 'For $k=0$, $0!=1$ and $3^0=1$.'),
    N('Independent Bernoulli variables have parameters .2 and .7. Enter $100E[X+Y]$.', 90, 'Linearity gives $E[X+Y]=.2+.7=.9$, so the scaled answer is 90.', 'No product is involved when adding expectations.', 0),
    N('A fair die value is $X$. Enter $12E[X]$.', 42, '$E[X]=(1+2+3+4+5+6)/6=3.5$; multiplying by 12 gives 42.', 'The support values, not just outcome counts, enter expectation.', 0),
    N('A random variable has $E[X]=4$ and $E[X^2]=22$. Enter $Var(X)$.', 6, '$Var(X)=E[X^2]-E[X]^2=22-16=6$.', 'Square the mean, not the second moment.', 0),
    N('Independent $X\\sim Bin(4,.5)$ and $Y\\sim Bin(6,.5)$. Enter $E[X+Y]$.', 5, 'The sum is $Bin(10,.5)$, or use linearity: $2+3=5$.', 'The common success probability is what also permits binomial aggregation.', 0),
    N('For $X\\sim Pois(4)$, enter $P(X=1)/P(X=0)$.', 4, 'The ratio is $(e^{-4}4)/(e^{-4})=4$.', 'Cancel the common exponential factor before approximating.', 0)
  ],

  'probability-statistics:4': [
    M('For a continuous random variable X, which statement is always true?', ['P(X=x)=f(x)', 'P(X=x)=0', 'f(x)≤1', 'F(x)<1 for every x'], 'B', 'A single point has zero area under a continuous density, so P(X=x)=0.', 'A density height can exceed one; probability is an integral.'),
    M('If X is Uniform(a,b), its density on (a,b) is', ['1/(a+b)', '1/(b−a)', 'b−a', 'x/(b−a)'], 'B', 'A constant density over length b−a must have height 1/(b−a).', 'Normalize by interval length, not endpoint sum.'),
    M('The derivative of an absolutely continuous CDF F is', ['the PMF', 'the density f almost everywhere', 'the survival function', 'the mean'], 'B', 'The density satisfies f(x)=F′(x) wherever the derivative exists.', 'The CDF is accumulated probability, not density.'),
    M('Which continuous distribution is memoryless?', ['Normal', 'Uniform', 'Exponential', 'Student t'], 'C', 'The exponential survival function satisfies P(X>s+t | X>s)=P(X>t).', 'Geometric is the discrete memoryless analogue.'),
    M('If X follows N(μ,σ²), then (X−μ)/σ follows', ['N(0,1)', 'N(0,σ)', 't with 1 df', 'chi-square with 1 df'], 'A', 'Centering by μ and scaling by the standard deviation produces a standard normal.', 'Divide by σ, not variance σ².'),
    M('The support of a chi-square random variable is', ['all real numbers', '[0,∞)', '(0,1)', 'integers only'], 'B', 'A chi-square variable is a sum of squared standard normals, hence nonnegative.', 'It is continuous despite integer degrees of freedom.'),
    S('Which are properties of every CDF?', ['Nondecreasing', 'Right-continuous', 'Limits 0 and 1 at negative and positive infinity', 'Differentiable everywhere'], ['A', 'B', 'C'], 'Every CDF has the first three properties. Jumps are allowed, so differentiability is not required.', 'Discrete CDFs have jumps.'),
    M('Compared with N(0,1), a Student t distribution has', ['lighter tails', 'heavier tails', 'only positive support', 'zero variance for every df'], 'B', 'Student t has heavier tails, reflecting uncertainty from estimating scale.', 'The t distribution is symmetric on the real line.'),
    M('For continuous X, P(a<X≤b) equals', ['F(a)−F(b)', 'F(b)−F(a)', 'f(b)−f(a)', 'F(a)F(b)'], 'B', 'CDF increments give interval probability F(b)−F(a).', 'Use CDF values, not density endpoint heights.'),
    M('If X follows Exp(λ) under the rate parameterization, E[X] is', ['λ', 'λ²', '1/λ', 'exp(−λ)'], 'C', 'The mean waiting time is the reciprocal of the event rate.', 'Some texts parameterize by mean; check the convention.'),
    N('A density is f(x)=cx² on 0<x<2. Enter c.', 0.375, 'Normalization gives c∫₀²x²dx=c(8/3)=1, hence c=3/8.', 'Integrate the density over its full support.', 0.0001),
    N('If X is Uniform(2,8), enter E[X].', 5, 'The continuous-uniform mean is the midpoint (2+8)/2=5.', 'Include both endpoints in the midpoint.', 0),
    N('If X is Uniform(2,8), enter Var(X).', 3, 'Variance is (b−a)²/12=36/12=3.', 'Variance uses squared interval length.', 0),
    N('If X follows Exp(0.5), enter −log P(X>4).', 2, 'P(X>4)=exp(−0.5·4)=exp(−2), so the negative log is 2.', 'Use the survival function, not the CDF.', 0),
    N('If X follows N(10,9), enter the z-score of X=16.', 2, 'The standard deviation is 3, so z=(16−10)/3=2.', 'The second normal parameter is variance here.', 0),
    N('A CDF is F(x)=x² on 0≤x≤1. Enter 10P(0.2<X≤0.6).', 3.2, 'The probability is 0.36−0.04=0.32; scaling gives 3.2.', 'Subtract CDF values, not endpoints.', 0.001),
    N('For exponential X, P(X>3)=0.4. Enter 100P(X>6 | X>3).', 40, 'Memorylessness gives P(X>6 | X>3)=P(X>3)=0.4.', 'Reset the remaining wait after conditioning.', 0),
    N('Three independent standard normals are squared and added. Enter the chi-square degrees of freedom.', 3, 'The sum of three independent squared standard normals is chi-square with 3 df.', 'Count the squared independent standard normals.', 0),
    N('If X follows N(4,16), enter Var((X−4)/4).', 1, 'Subtracting 4 changes no variance; dividing by 4 divides variance by 16.', 'Variance scales by the square.', 0),
    N('A density is f(x)=2x on 0<x<1. Enter its median.', 0.70710678, 'F(m)=m²=1/2, so m=1/√2≈0.7071.', 'Median splits probability area, not support length.', 0.001)
  ],

  'probability-statistics:5': [
    M('Which statistic is most resistant to one extreme outlier?', ['Mean', 'Median', 'Variance', 'Range'], 'B', 'The median depends on order, so one arbitrarily extreme value has limited influence.', 'Robustness differs from efficiency under a normal model.'),
    M('If 7 is added to every observation, the sample standard deviation', ['increases by 7', 'decreases by 7', 'is unchanged', 'is multiplied by 49'], 'C', 'A common shift changes location but not deviations from the mean.', 'Scaling, unlike shifting, changes standard deviation.'),
    M('Correlation is always between', ['0 and 1', '−1 and 1', 'negative and positive infinity', '−σXσY and σXσY'], 'B', 'Cauchy–Schwarz bounds correlation by −1 and 1.', 'Covariance is unbounded; correlation is standardized.'),
    M('If X,Y are independent with finite second moments, then', ['Cov(X,Y)=0', 'X=Y', 'Corr(X,Y)=1', 'Var(X)=Var(Y)'], 'A', 'Independence makes E[XY]=E[X]E[Y], hence zero covariance.', 'The converse is not generally true.'),
    M('For data 1,2,2,8, the mode is', ['1', '2', '3.25', '8'], 'B', 'The most frequent observed value is 2.', 'Mode is not mean or midpoint.'),
    M('Which identity is the law of total expectation?', ['E[X]=E[E[X|Y]]', 'E[X]=Var(E[X|Y])', 'E[X]=E[Var(X|Y)]', 'E[X|Y]=E[X] always'], 'A', 'Averaging the conditional expectation over Y recovers the unconditional mean.', 'The conditional expectation is itself a random variable in Y.'),
    S('Which transformations preserve correlation?', ['X→2X+1', 'Y→5Y−3', 'X→−X', 'Y→Y+100'], ['A', 'B', 'D'], 'Positive rescaling and shifts preserve correlation. Negating one variable reverses its sign.', 'A negative scale changes correlation sign.'),
    M('If Corr(X,Y)=0, which conclusion is always justified when SDs are positive?', ['X,Y are independent', 'Cov(X,Y)=0', 'Y is constant', 'E[XY]=0'], 'B', 'Zero correlation directly means zero covariance when defined.', 'Independence needs stronger assumptions.'),
    M('The usual unbiased sample variance uses denominator', ['n', 'n−1', 'n+1', '√n'], 'B', 'Bessel-corrected sample variance divides by n−1.', 'Population variance and likelihood conventions may use n.'),
    M('The law of total variance is', ['Var(X)=E[Var(X|Y)]+Var(E[X|Y])', 'Var(X)=E[Var(X|Y)]', 'Var(X)=Var(X|Y)+Var(Y)', 'Var(X)=E[X²]+E[X]²'], 'A', 'Total variance adds average within-group variance and variance between conditional means.', 'Do not drop the between-group term.'),
    N('Enter the mean of 2,4,6,8.', 5, 'Their sum is 20 across four values, so the mean is 5.', 'Divide by the observation count.', 0),
    N('Enter the population variance of 1,3,5.', 2.6666667, 'Mean is 3; squared deviations sum to 8, so population variance is 8/3.', 'Population variance divides by 3, not 2.', 0.001),
    N('Five values have mean 12. A sixth value 18 is added. Enter the new mean.', 13, 'Old sum is 60; new sum is 78, and 78/6=13.', 'Recover the total before updating.', 0),
    N('If E[X]=3 and E[X²]=14, enter Var(X).', 5, 'Var(X)=14−3²=5.', 'Subtract the square of the mean.', 0),
    N('If Cov(X,Y)=6, σX=2, and σY=3, enter Corr(X,Y).', 1, 'Correlation is 6/(2·3)=1.', 'Divide by the product of SDs.', 0),
    N('If Var(X)=4, enter Var(3X−7).', 36, 'Variance scales by 3², giving 9·4=36.', 'The shift does not affect variance.', 0),
    N('Given E[X]=2,E[Y]=5,E[XY]=13, enter Cov(X,Y).', 3, 'Covariance is 13−2·5=3.', 'Subtract the product of means.', 0),
    N('If E[Var(X|Y)]=4 and Var(E[X|Y])=7, enter Var(X).', 11, 'The law of total variance gives 4+7=11.', 'Both within- and between-group parts matter.', 0),
    N('For sorted data 1,2,3,4,100, enter the median.', 3, 'With five values, the third ordered value is the median.', 'An outlier affects mean more than median.', 0),
    N('If Corr(X,Y)=−0.8, enter Corr(2X+1,−3Y+4).', 0.8, 'One negative scale reverses the sign; shifts do nothing.', 'Track the signs of scale factors.', 0.001)
  ],

  'probability-statistics:6': [
    M('For iid observations with variance σ², Var(sample mean) is', ['σ²', 'σ²/n', 'σ/n', 'nσ²'], 'B', 'Variance of the average is nσ²/n²=σ²/n.', 'Standard error is σ/√n; variance is its square.'),
    M('The Central Limit Theorem primarily says that', ['raw observations become normal', 'a standardized sum tends toward normality', 'every sample mean equals μ', 'variance becomes zero at finite n'], 'B', 'Under suitable conditions, the centered and scaled sum converges in distribution to standard normal.', 'The population distribution itself does not change.'),
    M('If sample size is multiplied by 4, standard error is', ['multiplied by 4', 'multiplied by 2', 'halved', 'quartered'], 'C', 'Standard error is proportional to 1/√n.', 'It follows a square-root law.'),
    M('The law of large numbers concerns', ['convergence of sample mean to μ', 'exact normality of every sum', 'the t distribution only', 'maximum values'], 'A', 'The sample average stabilizes near the population mean as n grows.', 'LLN is about convergence, not fluctuation shape.'),
    M('For iid Xi with variance 9, Var(sum of 10 Xi) is', ['0.9', '9', '30', '90'], 'D', 'Independence makes variances add: 10·9=90.', 'Do not divide by n for a sum.'),
    M('Which condition is central to the classical iid CLT?', ['Finite variance', 'Normal population', 'n exactly above 30', 'Zero mean'], 'A', 'Finite variance supports the classical CLT; normal raw data and zero mean are unnecessary.', 'Thirty is a heuristic, not a theorem condition.'),
    S('For iid data with finite variance, which are true?', ['E[sample mean]=μ', 'Var(sample mean)=σ²/n', 'sample mean is exactly normal for every population and n', 'standard error decreases with n'], ['A', 'B', 'D'], 'The first two follow directly and standard error shrinks. Exact finite-n normality is not universal.', 'CLT normality is generally approximate.'),
    M('If the original population is normal, the sample mean is', ['exactly normal for every n', 'normal only for n≥30', 'uniform', 'chi-square'], 'A', 'Linear combinations of independent normals are exactly normal.', 'No large-sample approximation is needed.'),
    M('A continuity correction is used when approximating', ['a discrete count by a continuous normal', 'normal by t', 'mean by variance', 'exponential by uniform'], 'A', 'A 0.5 boundary shift aligns discrete bars with continuous area.', 'It addresses discrete-to-continuous boundaries.'),
    M('Consistency informally means an estimator', ['is always unbiased', 'gets close to the target as n grows', 'has variance growing with n', 'equals every sample value'], 'B', 'A consistent estimator concentrates around the true value.', 'Consistency is asymptotic and distinct from unbiasedness.'),
    N('Population SD is 15 and n=25. Enter standard error of the mean.', 3, 'SE=15/√25=3.', 'Use square root of sample size.', 0),
    N('iid variables have mean 4 and variance 9. For n=20, enter E[sum Xi].', 80, 'Expectation of the sum is 20·4=80.', 'Means add linearly.', 0),
    N('For the same variables and n=20, enter Var(sum Xi).', 180, 'Independence gives 20·9=180.', 'Sum variance multiplies by n.', 0),
    N('Population variance is 16 and n=64. Enter Var(sample mean).', 0.25, 'Variance of the mean is 16/64=0.25.', 'This asks variance, not standard error.', 0.001),
    N('The standardized mean is (sample mean−50)/(10/√100). If sample mean=52, enter z.', 2, 'The standard error is 1, so z=2.', 'Use sampling SD, not population SD alone.', 0),
    N('To reduce a standard error from 4 to 2, by what factor must n increase?', 4, 'Halving error requires quadrupling n.', 'Precision follows a square-root law.', 0),
    N('For iid Bernoulli(0.3) data, enter E[sample mean].', 0.3, 'The sample proportion is unbiased for p, so its mean is 0.3.', 'Averaging does not change expectation.', 0.001),
    N('For n=100 Bernoulli(0.3) data, enter 1000Var(sample mean).', 2.1, 'Variance is 0.3·0.7/100=0.0021; scaling gives 2.1.', 'Use p(1−p)/n.', 0.001),
    N('A sum has variance 1600. Enter its standard deviation.', 40, 'Standard deviation is √1600=40.', 'Take the square root of variance.', 0),
    N('If Z=(sample mean−μ)/(σ/√n) and sample mean=μ, enter Z.', 0, 'The numerator is zero.', 'Centering maps the mean to z=0.', 0)
  ],

  'probability-statistics:7': [
    M('A p-value is', ['the probability the null is true', 'the probability under H0 of data at least as extreme as observed', 'the Type II error rate', 'always equal to α'], 'B', 'The p-value is computed assuming the null and measures tail extremeness.', 'It is not a posterior probability of H0.'),
    M('At α=0.05, a p-value of 0.03 leads to', ['reject H0', 'accept H0 as true', 'increase α', 'no decision'], 'A', 'Because 0.03<0.05, reject H0.', 'Rejection is not proof of a scientific claim.'),
    M('For a small normal sample with unknown variance, a one-mean test uses', ['z', 't', 'chi-square independence', 'uniform'], 'B', 'Replacing unknown σ with s yields a t statistic with n−1 df.', 'Do not silently treat s as known σ.'),
    M('A Type I error means', ['failing to reject a false null', 'rejecting a true null', 'accepting a true null', 'using a two-sided test'], 'B', 'Type I error is a false positive.', 'Type II is failing to reject a false null.'),
    M('For an r×c contingency table, independence-test df is', ['rc', 'r+c−2', '(r−1)(c−1)', 'rc−1'], 'C', 'After marginal constraints, (r−1)(c−1) deviations are free.', 'Do not count every cell as free.'),
    M('A 95% confidence procedure means', ['95% of fixed parameters lie in one interval', '95% of intervals from repeated samples cover the parameter', 'H0 is true with probability .95', 'sample values lie within it'], 'B', 'Coverage is the long-run behavior of the random interval procedure.', 'The classical parameter is fixed.'),
    S('Which reduce a known-variance mean CI margin?', ['Increase n', 'Use lower confidence', 'Increase σ', 'Decrease critical value'], ['A', 'B', 'D'], 'Margin is critical value times σ/√n.', 'Higher confidence produces a wider interval.'),
    M('Statistical power is', ['P(reject H0 | H0 false)', 'P(reject H0 | H0 true)', '1−α always', 'the p-value'], 'A', 'Power is one minus Type II error under a specified alternative.', 'Type I probability under H0 is α.'),
    M('A two-sided alternative for μ0 is', ['μ>μ0', 'μ<μ0', 'μ≠μ0', 'μ=μ0'], 'C', 'Two-sided testing looks for departures in either direction.', 'Equality belongs in H0.'),
    M('Expected count in cell (i,j) under independence is', ['row+column total', 'row total×column total/grand total', 'observed/grand total', 'grand total/cells always'], 'B', 'Expected count is RiCj/N.', 'Equal expectations require equal margins.'),
    N('Known σ=10, n=100, sample mean=52. For H0:μ=50, enter z.', 2, 'z=(52−50)/(10/10)=2.', 'Use the standard error σ/√n.', 0),
    N('Sample mean=20, σ=4, n=16, z*=1.96. Enter the margin.', 1.96, 'Margin=1.96·4/4=1.96.', 'Margin is half interval width.', 0.001),
    N('A one-sample t test has n=12. Enter degrees of freedom.', 11, 'df=n−1=11.', 'One df is used estimating the mean.', 0),
    N('A chi-square independence test uses a 4×3 table. Enter df.', 6, '(4−1)(3−1)=6.', 'Subtract one before multiplying.', 0),
    N('Observed and expected counts are 12 and 8. Enter the chi-square contribution.', 2, '(12−8)²/8=2.', 'Square the difference.', 0),
    N('If α=.05, enter 100P(Type I error) for an exact-size test.', 5, 'Type I probability equals α=.05; scaling gives 5.', 'Condition on H0 being true.', 0),
    N('A 90% z interval has z*=1.645, σ=6, n=36. Enter margin.', 1.645, 'Margin=1.645·6/6=1.645.', 'Use the supplied two-sided critical value.', 0.001),
    N('To halve a known-variance interval margin, by what factor must n change?', 4, 'Margin scales as 1/√n.', 'Doubling n only multiplies margin by 1/√2.', 0),
    N('In a table with row total 40, column total 30, grand total 100, enter expected count.', 12, 'Expected count is 40·30/100=12.', 'Use both margins.', 0),
    N('A test has power 0.8. Enter its Type II error probability.', 0.2, 'Power=1−β, so β=.2.', 'Do not confuse β with α.', 0.001)
  ],

  'linear-algebra:1': [
    M('Which subset of R² is a subspace?', ['{(x,y):x+y=1}', '{(x,y):x=2y}', '{(x,y):x≥0}', '{(x,y):xy=0}'], 'B', 'The equation x−2y=0 is homogeneous and its solution set is closed under linear combinations.', 'A set through the origin can still fail closure; verify both operations.'),
    M('A basis of R³ must contain', ['exactly 2 vectors', 'exactly 3 linearly independent vectors', 'any 3 vectors', 'at least 4 vectors'], 'B', 'Dimension of R³ is 3, so every basis has exactly three independent spanning vectors.', 'Correct cardinality alone does not guarantee a basis.'),
    M('A set containing the zero vector is necessarily', ['independent', 'dependent', 'a basis', 'a subspace'], 'B', 'Give the zero vector coefficient 1 and all others 0 to obtain a nontrivial zero combination.', 'Containing zero does not itself make a set a subspace.'),
    M('The span of one nonzero vector in R³ is geometrically', ['a point', 'a line through the origin', 'a plane not through origin', 'all of R³'], 'B', 'All scalar multiples of one nonzero vector form a line through zero.', 'A span always contains the origin.'),
    M('Polynomials of degree at most 2 have dimension', ['2', '3', '4', 'infinite'], 'B', '{1,x,x²} is a basis, so the dimension is 3.', 'Count coefficients, including the constant term.'),
    M('If three vectors in R² are given, they are always', ['orthogonal', 'linearly dependent', 'a basis', 'zero'], 'B', 'No independent set can contain more vectors than the ambient dimension 2.', 'The vectors need not include zero to be dependent.'),
    S('For subspaces U,W of a vector space, which are always subspaces?', ['U∩W', 'U+W', 'U∪W', '{0}'], ['A', 'B', 'D'], 'Intersection and sum preserve linear combinations, and {0} is the zero subspace. A union fails closure unless one subspace contains the other.', 'Union is the classic trap.'),
    M('Coordinates of a vector relative to a basis are', ['never unique', 'unique', 'unique only for orthogonal bases', 'always the original components'], 'B', 'Independence gives uniqueness and spanning gives existence.', 'An orthogonal basis is convenient, not required.'),
    M('If span(S)=V and one vector in S is a combination of the others, then', ['S is minimal', 'that vector can be removed without changing the span', 'V is zero', 'S is independent'], 'B', 'A redundant vector contributes no new direction and can be deleted.', 'Spanning sets may contain redundancy.'),
    M('The solution set of Ax=0 is', ['always a subspace', 'a subspace only if A is square', 'never a subspace', 'an affine set not through zero'], 'A', 'The null space contains zero and is closed because A(αx+βy)=0.', 'Squareness is irrelevant.'),
    N('Enter the dimension of span{(1,0,0),(0,1,0),(1,1,0)}.', 2, 'The third vector is the sum of the first two; the first two are independent.', 'Count independent directions, not listed vectors.', 0),
    N('If dim U=4, dim W=3, and dim(U∩W)=2, enter dim(U+W).', 5, 'Dimension formula gives 4+3−2=5.', 'Subtract overlap to avoid double counting.', 0),
    N('Enter the dimension of {x in R⁴:x1+x2+x3+x4=0}.', 3, 'One independent homogeneous constraint in R⁴ leaves three free variables.', 'A homogeneous hyperplane through zero has codimension one.', 0),
    N('For what value a are (1,2) and (a,4) linearly dependent?', 2, 'Dependence requires (a,4)=2(1,2), hence a=2.', 'Match the same scalar across both coordinates.', 0),
    N('Enter the dimension of 2×3 real matrices as a vector space.', 6, 'Each of six entries is a free coordinate, so dimension is 2·3=6.', 'Matrix dimensions multiply for vector-space dimension.', 0),
    N('If U is a 2D subspace of R⁵, enter the maximum number of linearly independent vectors in U.', 2, 'By definition, no independent subset of U exceeds dim U=2.', 'Ambient dimension does not override subspace dimension.', 0),
    N('Enter the dimension of the solution space of x+y+z=0 and x−y=0 in R³.', 1, 'The two independent constraints leave one free parameter: x=y=t,z=−2t.', 'Check constraint independence before subtracting their count.', 0),
    N('If a list of 5 vectors has rank 3, enter the number of vectors in a basis extracted from it.', 3, 'Rank is the dimension of the span, hence an extracted basis has 3 vectors.', 'A basis removes redundant vectors.'),
    N('Enter dim(U∩W) if U and W are distinct planes through the origin in R³ whose sum is R³.', 1, 'The dimension formula gives 2+2−3=1; the planes intersect in a line.', 'Distinct planes through the origin cannot be disjoint.'),
    N('Enter the dimension of symmetric 3×3 real matrices.', 6, 'Three diagonal and three upper-triangular entries are free; symmetry determines the rest.', 'Off-diagonal pairs contribute one degree each, not two.', 0)
  ],

  'linear-algebra:2': [
    M('If Q is orthogonal, then Q inverse equals', ['Q', 'Q transpose', '−Q', 'det(Q)'], 'B', 'QᵀQ=I, so Qᵀ is the inverse.', 'Q need not be symmetric.'),
    M('An idempotent matrix P satisfies', ['P²=I', 'P²=P', 'PᵀP=I', 'P=0 only'], 'B', 'Idempotence is exactly P²=P.', 'Involution P²=I is a different property.'),
    M('Eigenvalues of an idempotent matrix belong to', ['{−1,1}', '{0,1}', 'positive reals only', 'complex unit circle'], 'B', 'P²v=Pv gives λ²=λ, hence λ is 0 or 1.', 'Idempotent does not imply invertible.'),
    M('A real orthogonal matrix preserves', ['only determinant', 'Euclidean lengths and inner products', 'every coordinate', 'trace'], 'B', '(Qx)ᵀ(Qy)=xᵀQᵀQy=xᵀy.', 'Rotation can change coordinates while preserving geometry.'),
    M('An orthogonal projection matrix is', ['symmetric and idempotent', 'skew-symmetric', 'always invertible', 'always rank zero'], 'A', 'Orthogonal projections satisfy Pᵀ=P and P²=P.', 'An oblique projection may be idempotent without symmetry.'),
    M('The determinant of a real orthogonal matrix is', ['0', '1 only', '−1 or 1', 'any positive value'], 'C', 'det(QᵀQ)=det(Q)²=1.', 'Reflections have determinant −1.'),
    S('Which statements hold for an orthogonal projection P?', ['P²=P', 'Pᵀ=P', 'I−P is an orthogonal projection', 'Every eigenvalue equals 1'], ['A', 'B', 'C'], 'P and I−P project onto complementary orthogonal subspaces. P can have both 0 and 1 eigenvalues.', 'Projection rank need not equal full dimension.'),
    M('If P projects onto a k-dimensional subspace, trace(P) equals', ['0', '1', 'k', 'ambient dimension always'], 'C', 'The spectrum contains k ones and remaining zeros, so trace is k.', 'Trace equals rank for a projection.'),
    M('For nonzero vector a, projection onto span(a) is', ['aaᵀ', 'aaᵀ/(aᵀa)', 'aᵀa', 'I−aaᵀ always'], 'B', 'Normalization by aᵀa makes the map idempotent and fixes a.', 'aaᵀ works only when a is unit length.'),
    M('Which matrix is necessarily symmetric?', ['A+Aᵀ', 'A−Aᵀ', 'AB', 'A inverse'], 'A', '(A+Aᵀ)ᵀ=A+Aᵀ.', 'A−Aᵀ is skew-symmetric.'),
    N('Enter det(Q)² for any real orthogonal square matrix Q.', 1, 'From QᵀQ=I, determinants give det(Q)²=1.', 'The determinant itself can be −1.', 0),
    N('P is a 5×5 projection of rank 2. Enter trace(P).', 2, 'A projection has rank-many eigenvalues 1, so trace equals rank.', 'Count both zero and one eigenvalues correctly.', 0),
    N('For P=[[1,0],[0,0]], enter the squared norm of P(3,4)ᵀ.', 9, 'P(3,4)=(3,0), whose squared norm is 9.', 'Projection discards the orthogonal component.'),
    N('If Q is orthogonal and x has norm 7, enter norm(Qx).', 7, 'Orthogonal maps preserve Euclidean norm.', 'They do not scale length by determinant.', 0),
    N('Enter rank of the 3×3 all-ones matrix.', 1, 'Every row is the same nonzero row, so the row space is one-dimensional.', 'Nonzero entry count is unrelated to rank.', 0),
    N('P is idempotent and invertible. Enter trace(P) for a 4×4 P.', 4, 'P²=P and invertibility imply P=I, whose trace is 4.', 'An invertible projection has no zero eigendirections.', 0),
    N('Enter the rank of diag(1,0,1,0,1).', 3, 'There are three nonzero diagonal pivots.', 'Zeros contribute no rank.', 0),
    N('For unit a=(3/5,4/5), enter 25 times the (1,1) entry of aaᵀ.', 9, 'The (1,1) entry is (3/5)²=9/25; scaling gives 9.', 'Outer product entries multiply coordinates.'),
    N('If A is 2×3 and B is 3×4, enter the number of entries in AB.', 8, 'AB is 2×4, hence has 8 entries.', 'Inner dimensions cancel; outer dimensions remain.'),
    N('A 6×6 orthogonal projection has nullity 4. Enter its trace.', 2, 'Rank-nullity gives rank 2, and projection trace equals rank.', 'Use ambient column count 6.', 0)
  ],

  'linear-algebra:3': [
    M('A system Ax=b is consistent exactly when', ['rank(A)<rank([A|b])', 'rank(A)=rank([A|b])', 'A is square', 'b is nonzero'], 'B', 'Equal ranks mean the augmented column introduces no contradiction.', 'A rectangular system can be consistent.'),
    M('For an m×n matrix, rank plus nullity equals', ['m', 'n', 'm+n', 'min(m,n)'], 'B', 'Rank-nullity for the map from Rⁿ uses domain dimension n.', 'Use the number of columns.'),
    M('A row [0 0 0 | 5] in an augmented echelon matrix means', ['a free variable', 'a unique solution', 'inconsistency', 'rank zero'], 'C', 'It represents the impossible equation 0=5.', 'The augmented entry matters.'),
    M('Elementary row operations preserve', ['the exact columns', 'the solution set of an augmented system', 'all eigenvalues', 'the determinant unchanged in every case'], 'B', 'Each row operation produces an equivalent system.', 'Row swaps/scalings can change determinant.'),
    M('If a square n×n matrix has rank n, then Ax=b has', ['no solution for some b', 'a unique solution for every b', 'infinitely many solutions', 'only the zero solution for every b'], 'B', 'Full rank makes A invertible.', 'For nonzero b, the unique solution need not be zero.'),
    M('A pivot column in row echelon form corresponds to', ['a free variable', 'a basic variable', 'an inconsistent row', 'a zero column always'], 'B', 'Pivot positions identify leading/basic variables.', 'Non-pivot columns correspond to free variables.'),
    S('Which operations are valid elementary row operations?', ['Swap two rows', 'Multiply a row by a nonzero scalar', 'Add a multiple of one row to another', 'Square every entry in a row'], ['A', 'B', 'C'], 'The first three are reversible linear row operations. Entrywise squaring is nonlinear.', 'A row scale cannot use zero.'),
    M('The null space of A contains', ['solutions of Ax=0', 'columns of A only', 'solutions of Ax=b for every b', 'row vectors only'], 'A', 'Null(A) is defined as all domain vectors mapped to zero.', 'Null vectors live in the domain.'),
    M('If Ax=b has one solution xp, then every solution is', ['xp plus a null-space vector', 'only xp', 'a row-space vector', 'xp times b'], 'A', 'If Ax=b and Axp=b, then A(x−xp)=0.', 'The homogeneous component describes all freedom.'),
    M('Row rank and column rank of a matrix are', ['always equal', 'equal only when square', 'unrelated', 'both equal nullity'], 'A', 'Both equal the matrix rank for every finite matrix.', 'The row and column spaces themselves differ, but dimensions agree.'),
    N('A 4×7 matrix has rank 3. Enter its nullity.', 4, 'Nullity=7−3=4.', 'Use the number of columns.', 0),
    N('A homogeneous system has 6 variables and 4 pivots. Enter its number of free variables.', 2, 'Free variables=6−4=2.', 'Rows do not determine the count directly.', 0),
    N('Enter rank of [[1,2],[2,4]].', 1, 'The second row is twice the first and the matrix is nonzero.', 'Dependent rows reduce rank to one, not zero.', 0),
    N('Enter nullity of the 3×3 identity matrix.', 0, 'Identity has rank 3, so nullity is 0.', 'Only the zero vector maps to zero.', 0),
    N('The RREF of a 3×5 matrix has 2 pivots. Enter dimension of its row space.', 2, 'Row-space dimension equals rank, the pivot count.', 'Nonzero RREF rows form a row-space basis.', 0),
    N('Enter the rank of a nonzero 4×4 matrix whose every row is a scalar multiple of the first.', 1, 'All rows span one nonzero direction.', 'Nonzero prevents rank zero.', 0),
    N('A 3×4 matrix A has rank 3. Enter dimension of its left null space Null(Aᵀ).', 0, 'Aᵀ has 3 columns and rank 3, so its nullity is 0; equivalently m−rank=3−3.', 'Left nullity uses number of rows of A.', 0),
    N('If rank(A)=rank([A|b])=2 and A has 5 columns, enter the number of free variables.', 3, 'The system is consistent and has 5−2=3 free variables.', 'Equal ranks establish consistency; columns minus rank gives freedom.', 0),
    N('Enter rank of a 5×3 matrix with three linearly independent columns.', 3, 'Independent columns give column-space dimension 3.', 'Rank cannot exceed the three columns.', 0),
    N('A linear system in 4 unknowns has a unique solution. Enter nullity of its coefficient matrix.', 0, 'Uniqueness means the associated homogeneous system has only zero solution.', 'Consistency alone would not force nullity zero.', 0)
  ],

  'linear-algebra:4': [
    M('The determinant of a triangular matrix equals', ['sum of diagonal entries', 'product of diagonal entries', 'largest diagonal entry', 'rank'], 'B', 'Only the identity permutation contributes, giving the diagonal product.', 'Trace is the diagonal sum.'),
    M('Swapping two rows of A', ['leaves det unchanged', 'negates det', 'squares det', 'makes det zero'], 'B', 'One row interchange multiplies the determinant by −1.', 'Two swaps would restore the sign.'),
    M('Adding a multiple of one row to another', ['leaves det unchanged', 'always makes det zero', 'multiplies det by that multiple', 'negates det'], 'A', 'Row replacement preserves determinant.', 'Row scaling is the operation that scales determinant.'),
    M('A square matrix is invertible exactly when', ['det=0', 'det≠0', 'trace=0', 'all entries are nonzero'], 'B', 'Nonzero determinant is equivalent to full rank and invertibility.', 'Zero entries can occur in invertible matrices.'),
    M('Which identity is valid?', ['det(A+B)=det(A)+det(B)', 'det(AB)=det(A)det(B)', 'det(Aᵀ)=−det(A)', 'det(2A)=2det(A) for all sizes'], 'B', 'Determinants multiply over matrix products.', 'Determinant is not additive.'),
    M('If A is 3×3, det(2A) equals', ['2det(A)', '4det(A)', '8det(A)', 'det(A)+2'], 'C', 'Scaling all three rows by 2 multiplies determinant by 2³=8.', 'The scalar factor is raised to matrix order.'),
    S('If det(A)=0 for square A, which are true?', ['Columns are dependent', 'A is singular', 'Ax=0 has a nonzero solution', 'A has an inverse'], ['A', 'B', 'C'], 'Zero determinant, dependence, singularity, and a nontrivial null space are equivalent.', 'Invertibility requires nonzero determinant.'),
    M('det(Aᵀ) is', ['det(A)', '−det(A)', '1/det(A)', '0'], 'A', 'Transposition does not change the permutation expansion value.', 'Transpose preserves determinant.'),
    M('If det(A)=−2, then det(A inverse) is', ['2', '−2', '1/2', '−1/2'], 'D', 'The inverse determinant is the reciprocal, −1/2.', 'Keep the original sign when taking reciprocal.'),
    M('The absolute determinant of a linear map gives', ['rank only', 'volume scaling factor', 'trace', 'number of eigenvectors'], 'B', 'Absolute determinant scales n-dimensional volume.', 'The sign records orientation.'),
    N('Enter det([[3,0],[0,5]]).', 15, 'The diagonal product is 3·5=15.', 'Off-diagonal zeros make this immediate.', 0),
    N('Enter det([[1,2],[3,4]]).', -2, 'For 2×2, det=1·4−2·3=−2.', 'Respect the subtraction order ad−bc.', 0),
    N('If det(A)=3 and det(B)=−2, enter det(AB).', -6, 'Multiplicativity gives 3(−2)=−6.', 'Matrix products need not commute, but determinant products do.', 0),
    N('For 4×4 A with det(A)=2, enter det(3A).', 162, 'det(3A)=3⁴·2=81·2=162.', 'Scale factor applies once per row.', 0),
    N('If det(A)=5, enter det(AᵀA).', 25, 'det(AᵀA)=det(Aᵀ)det(A)=5²=25.', 'Transpose does not change determinant.', 0),
    N('A matrix is obtained from det(A)=7 by two row swaps. Enter its determinant.', 7, 'Each swap changes sign, so two swaps multiply by (−1)²=1.', 'Count swap parity.', 0),
    N('Enter det of a 3×3 matrix with two identical rows.', 0, 'Swapping identical rows changes no matrix but would negate determinant; therefore it is zero.', 'Repeated rows are dependent.', 0),
    N('Eigenvalues of a 3×3 matrix are 2,3,−1. Enter its determinant.', -6, 'Determinant is the product of eigenvalues: 2·3·(−1)=−6.', 'Count eigenvalues with algebraic multiplicity.', 0),
    N('If det(A)=4, enter det(A² inverse).', 0.0625, 'det((A²)⁻¹)=1/det(A²)=1/4²=1/16.', 'Apply both the power and reciprocal.', 0.0001),
    N('Enter the determinant of the 4×4 identity matrix.', 1, 'The diagonal product is 1.', 'Identity determinant is one in every dimension.', 0)
  ],

  'linear-algebra:5': [
    M('An eigenvector must be', ['nonzero', 'unit length', 'orthogonal to all others', 'unique'], 'A', 'The zero vector satisfies Av=λv for every λ and is excluded to keep the concept meaningful.', 'Normalization is optional.'),
    M('Eigenvalues of a triangular matrix are', ['row sums', 'diagonal entries', 'singular values', 'column norms'], 'B', 'The characteristic determinant of a triangular matrix is the product of diagonal shifts.', 'Off-diagonal entries can affect eigenvectors but not eigenvalues.'),
    M('For a real symmetric matrix, eigenvalues are', ['always complex nonreal', 'real', 'always positive', 'all equal'], 'B', 'The spectral theorem guarantees real eigenvalues.', 'Symmetry does not imply positive definiteness.'),
    M('Eigenvectors for distinct eigenvalues of a real symmetric matrix are', ['parallel', 'orthogonal', 'zero', 'identical'], 'B', 'Symmetry makes eigenspaces for distinct eigenvalues orthogonal.', 'This orthogonality need not hold for nonsymmetric matrices.'),
    M('A matrix is diagonalizable when it has', ['nonzero determinant only', 'enough linearly independent eigenvectors', 'distinct entries', 'zero trace'], 'B', 'An n×n matrix needs n independent eigenvectors to form the diagonalizing basis.', 'Invertibility and diagonalizability are different.'),
    M('Trace equals', ['product of eigenvalues', 'sum of eigenvalues with multiplicity', 'largest eigenvalue', 'rank always'], 'B', 'The characteristic polynomial coefficients give trace as eigenvalue sum.', 'Determinant is the eigenvalue product.'),
    S('For A=PDP inverse, which are true?', ['A and D have the same eigenvalues', 'Aᵏ=PDᵏP inverse', 'Columns of P are eigenvectors', 'D must equal identity'], ['A', 'B', 'C'], 'Similarity preserves spectrum, P collects an eigenbasis, and powers act on D.', 'D stores eigenvalues and need not be identity.'),
    M('A repeated eigenvalue guarantees diagonalizability', ['always', 'never', 'only if geometric multiplicity reaches algebraic multiplicity', 'only if determinant is zero'], 'C', 'Every eigenvalue must supply enough independent eigenvectors.', 'Repetition alone does not decide diagonalizability.'),
    M('If Av=λv, then A²v equals', ['λv', '2λv', 'λ²v', '0 always'], 'C', 'A²v=A(λv)=λAv=λ²v.', 'The power applies to the eigenvalue.'),
    M('Zero is an eigenvalue exactly when A is', ['orthogonal', 'singular', 'symmetric', 'diagonal'], 'B', 'Av=0 has a nonzero solution exactly when A is singular.', 'A symmetric matrix can be invertible.'),
    N('Enter eigenvalue sum of a matrix with trace 9.', 9, 'Eigenvalues sum to trace, counting algebraic multiplicity.', 'No diagonalization is needed.', 0),
    N('A 3×3 matrix has eigenvalues 1,2,4. Enter its determinant.', 8, 'The product is 1·2·4=8.', 'Determinant uses product, not sum.', 0),
    N('Enter the largest eigenvalue of diag(−2,5,3).', 5, 'Diagonal entries are the eigenvalues.', 'Largest means algebraically largest here.', 0),
    N('If Av=3v, enter the eigenvalue of A⁵ for the same v.', 243, 'A⁵v=3⁵v=243v.', 'Raise the eigenvalue to the power.', 0),
    N('A 2×2 matrix has trace 7 and one eigenvalue 2. Enter the other.', 5, 'The eigenvalues sum to 7, so the other is 5.', 'Trace counts multiplicity.', 0),
    N('A 2×2 matrix has determinant 12 and one eigenvalue 3. Enter the other.', 4, 'Eigenvalue product is 12, so the other is 4.', 'Use determinant for product.', 0),
    N('Enter the geometric multiplicity of eigenvalue 1 for [[1,1],[0,1]].', 1, 'A−I has rank 1, so its null space is one-dimensional.', 'Algebraic multiplicity is 2 but geometric multiplicity is 1.', 0),
    N('A real symmetric 4×4 matrix has four distinct eigenvalues. Enter the maximum size of an orthonormal eigenbasis.', 4, 'The spectral theorem supplies four orthonormal eigenvectors.', 'Distinctness already gives independent vectors; symmetry gives orthogonality.', 0),
    N('If eigenvalues of A are 2 and −1, enter trace(A³).', 7, 'Eigenvalues of A³ are 8 and −1, so trace is 7.', 'Cube eigenvalues before summing.', 0),
    N('Enter the spectral radius of diag(−6,2,5).', 6, 'Spectral radius is maximum absolute eigenvalue: max(6,2,5)=6.', 'Use absolute magnitude, not largest signed value.', 0)
  ],

  'linear-algebra:6': [
    M('A symmetric matrix is positive definite exactly when', ['all eigenvalues are positive', 'all entries are positive', 'determinant alone is positive', 'trace is positive'], 'A', 'For symmetric A, xᵀAx>0 for all nonzero x iff every eigenvalue is positive.', 'Positive trace or determinant alone is insufficient.'),
    M('A positive semidefinite matrix may have eigenvalues', ['only strictly positive', 'nonnegative, including zero', 'only negative', 'nonreal'], 'B', 'Semidefinite permits zero curvature directions.', 'Strict positivity characterizes positive definite.'),
    M('For skew-symmetric K, xᵀKx equals', ['1', 'det(K)', '0', 'norm(x)'], 'C', 'The scalar equals its transpose, which is its negative, so it must be zero.', 'This holds for every real x.'),
    M('The matrix representing 2x²+6xy+5y² is', ['[[2,6],[0,5]]', '[[2,3],[3,5]]', '[[2,6],[6,5]]', '[[1,3],[3,5]]'], 'B', 'The cross term is 2a12xy, so a12=3.', 'Split the cross coefficient equally across symmetric off-diagonals.'),
    M('An indefinite quadratic form takes', ['only positive values', 'only negative values', 'both positive and negative values', 'only zero'], 'C', 'Indefinite means there are directions with opposite signs.', 'A zero direction alone indicates semidefiniteness, not indefiniteness.'),
    M('Sylvester’s criterion for symmetric positive definiteness requires', ['all leading principal minors positive', 'determinant positive only', 'trace zero', 'all diagonal entries negative'], 'A', 'Every leading principal minor must be strictly positive.', 'The full determinant is only the last condition.'),
    S('Which symmetric diagonal matrices are positive semidefinite?', ['diag(1,0,2)', 'diag(0,0,0)', 'diag(1,−1,2)', 'diag(4,3,2)'], ['A', 'B', 'D'], 'Diagonal eigenvalues are the diagonal entries; PSD means each is nonnegative.', 'One negative entry makes the form negative along that axis.'),
    M('At a stationary point, a positive-definite Hessian implies', ['strict local minimum', 'strict local maximum', 'saddle always', 'nothing'], 'A', 'Positive curvature in every direction gives a strict local minimum.', 'The stationary-point condition is also needed.'),
    M('Only which part of A affects xᵀAx?', ['symmetric part', 'skew part', 'upper triangle without reflection', 'determinant'], 'A', 'xᵀAx equals xᵀ((A+Aᵀ)/2)x because the skew part vanishes.', 'A nonsymmetric representation can be symmetrized.'),
    M('If A is positive definite, then A is', ['singular', 'invertible', 'zero', 'skew-symmetric'], 'B', 'All eigenvalues are positive and hence nonzero.', 'Positive definite is stronger than invertible.'),
    N('For q=3x²+4xy+2y², enter the off-diagonal entry in its symmetric matrix.', 2, 'The cross coefficient is 2a12=4, so a12=2.', 'Halve the xy coefficient.', 0),
    N('Enter xᵀAx for A=diag(2,3) and x=(1,2).', 14, 'The form is 2·1²+3·2²=2+12=14.', 'Square vector components.', 0),
    N('A symmetric 2×2 matrix has eigenvalues 4 and −1. Enter the number of positive eigenvalues.', 1, 'Exactly one eigenvalue is positive; the form is indefinite.', 'Count signs with multiplicity.', 0),
    N('Enter the smallest eigenvalue of diag(5,0,2).', 0, 'Diagonal entries are eigenvalues, and the smallest is zero.', 'PSD need not be strictly positive.'),
    N('For A=[[2,1],[1,2]], enter its determinant.', 3, 'det(A)=4−1=3; together with leading minor 2>0 this confirms positive definiteness.', 'A positive determinant alone would not suffice in higher dimensions.', 0),
    N('Enter q(1,−1) for q(x,y)=x²+2xy+y².', 0, 'q=(x+y)², so at (1,−1) it is zero.', 'This form is semidefinite, not definite.', 0),
    N('A positive-definite 3×3 matrix has eigenvalues 1,2,a. Enter the smallest integer a allowed.', 1, 'Positive definiteness requires a>0; the smallest positive integer is 1.', 'Zero would make it only semidefinite.', 0),
    N('If A has eigenvalues −2,−3, enter the number of negative eigenvalues of −A.', 0, 'Negation changes them to 2 and 3, both positive.', 'Every eigenvalue changes sign.', 0),
    N('Enter xᵀKx for any real skew-symmetric K and x.', 0, 'The quadratic form of a real skew-symmetric matrix always vanishes.', 'Do not infer K itself is zero.', 0),
    N('A symmetric matrix has inertia (2 positive,1 zero,3 negative). Enter its dimension.', 6, 'Inertia counts all eigenvalue signs: 2+1+3=6.', 'Include the zero eigenvalues.', 0)
  ],

  'linear-algebra:7': [
    M('Singular values of A are square roots of eigenvalues of', ['A', 'A+Aᵀ', 'AᵀA', 'A inverse'], 'C', 'AᵀA is PSD and its eigenvalue square roots are singular values.', 'Eigenvalues of A itself can be negative or complex.'),
    M('Singular values are always', ['negative', 'nonnegative', 'complex nonreal', 'equal to eigenvalues'], 'B', 'They are defined as nonnegative square roots.', 'A negative eigenvalue does not produce a negative singular value.'),
    M('In A=UΣVᵀ, columns of V are', ['left singular vectors', 'right singular vectors', 'rows of A', 'eigenvalues'], 'B', 'V contains right singular vectors, eigenvectors of AᵀA.', 'U contains left singular vectors.'),
    M('Matrix rank equals', ['number of nonzero singular values', 'largest singular value', 'sum of singular values', 'number of rows always'], 'A', 'Each nonzero singular value contributes one independent mapped direction.', 'Tiny numerical values may need a tolerance in computation.'),
    M('The best rank-k approximation in Frobenius norm is obtained by', ['keeping k smallest singular values', 'truncating to k largest singular values', 'zeroing diagonal of A', 'using LU only'], 'B', 'Eckart–Young says the truncated SVD is optimal.', 'Largest components carry the most energy.'),
    M('LU decomposition primarily factors A into', ['two orthogonal matrices', 'lower and upper triangular matrices', 'eigenvectors and eigenvalues', 'two diagonal matrices'], 'B', 'Elimination multipliers form L and the echelon result is U.', 'SVD is the orthogonal-diagonal-orthogonal factorization.'),
    S('Which statements about SVD are true?', ['Exists for every real rectangular matrix', 'Reveals rank', 'Supports a pseudoinverse', 'Requires A to be symmetric'], ['A', 'B', 'C'], 'SVD exists for any real matrix and directly supports rank and pseudoinverse computations.', 'Symmetry is not required.'),
    M('If a zero pivot occurs during LU without pivoting, one may need', ['row permutation', 'complex numbers always', 'SVD deletion', 'to make A symmetric'], 'A', 'Partial pivoting permutes rows, leading to PA=LU.', 'A zero pivot does not imply the original matrix is singular.'),
    M('The squared Frobenius norm equals', ['sum of singular values', 'sum of squared singular values', 'largest singular value only', 'determinant'], 'B', 'Frobenius energy is Σσi².', 'Nuclear norm is the unsquared sum.'),
    M('For centered data matrix X, PCA directions are tied to', ['right singular vectors of X', 'LU multipliers', 'row swaps only', 'null vectors only'], 'A', 'Right singular vectors are eigenvectors of XᵀX, the unscaled covariance structure.', 'Centering is essential before standard PCA.'),
    N('Enter singular values sum for diag(3,−2).', 5, 'Singular values are |3| and |−2|, summing to 5.', 'Do not preserve the negative sign.', 0),
    N('A matrix has singular values 5,2,0. Enter its rank.', 2, 'Exactly two singular values are nonzero.', 'Rank counts nonzero values, not their sum.', 0),
    N('A matrix has singular values 4,3. Enter its squared Frobenius norm.', 25, 'The squared Frobenius norm is 4²+3²=25.', 'Square before summing.', 0),
    N('For singular values 8,3,1, enter the spectral-norm error of the best rank-1 approximation.', 3, 'The discarded largest singular value is σ2=3.', 'Spectral error differs from Frobenius error.', 0),
    N('For singular values 8,3,1, enter squared Frobenius error of the best rank-1 approximation.', 10, 'Discarded energy is 3²+1²=10.', 'Frobenius error aggregates all discarded components.', 0),
    N('For nonsingular A with σmax=12 and σmin=3, enter its 2-norm condition number.', 4, 'κ2=σmax/σmin=12/3=4.', 'Use the smallest nonzero singular value.', 0),
    N('Enter the elimination multiplier for row 2 when A=[[2,1],[6,5]] is factored by LU.', 3, 'The multiplier is a21/a11=6/2=3.', 'Use the pivot before elimination.', 0),
    N('For A=[[2,1],[6,5]], enter the second diagonal pivot of U.', 2, 'Row2−3Row1 gives [0,2], so u22=2.', 'Apply the multiplier to the full row.', 0),
    N('A 7×4 matrix has full column rank. Enter number of positive singular values.', 4, 'Full column rank is 4, hence four nonzero positive singular values.', 'There can be at most min(7,4)=4 singular values.'),
    N('A rank-2 matrix has shape 5×8. Enter rank of its Moore–Penrose pseudoinverse.', 2, 'The pseudoinverse reciprocates nonzero singular values and preserves rank.', 'Its shape changes to 8×5, but rank does not.', 0)
  ]
};
